In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path

In [3]:
# Importar los datos de Airbnb desde las URLs indicadas en el documento de objetivos
url_listings = "https://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2025-06-12/visualisations/listings.csv"
url_listings_det = "https://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2025-06-12/data/listings.csv.gz"

listings = pd.read_csv(url_listings)
listings_det = pd.read_csv(url_listings_det, compression='gzip')

In [4]:
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,21853,Bright and airy room,83531,Abdel,Latina,Cármenes,40.40381,-3.74130,Private room,29.0,4,33,2018-07-15,0.25,2,340,0,NaN
1,30320,Apartamentos Dana Sol,130907,Dana,Centro,Sol,40.41476,-3.70418,Entire home/apt,NaN,5,172,2022-09-26,0.94,3,337,0,NaN
2,30959,Beautiful loft in Madrid Center,132883,Angela,Centro,Embajadores,40.41259,-3.70105,Entire home/apt,NaN,3,8,2017-05-30,0.06,1,0,0,NaN
3,40916,Apartasol Apartamentos Dana,130907,Dana,Centro,Universidad,40.42247,-3.70577,Entire home/apt,NaN,5,49,2021-12-11,0.27,3,352,0,NaN
4,62423,MAGIC ARTISTIC HOUSE IN THE CENTER OF MADRID,303845,Arturo,Centro,Justicia,40.41884,-3.69655,Private room,64.0,1,234,2025-06-07,2.70,3,314,34,NaN

In [5]:
listings.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [6]:
a_eliminar = ['host_id', 'host_name', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count','number_of_reviews_ltm', 'license']

# Eliminar las columnas innecesarias
listings = listings.drop(columns=a_eliminar)

In [7]:
listings.head()

,id,name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,availability_365
0,21853,Bright and airy room,Latina,Cármenes,40.40381,-3.74130,Private room,29.0,4,340
1,30320,Apartamentos Dana Sol,Centro,Sol,40.41476,-3.70418,Entire home/apt,NaN,5,337
2,30959,Beautiful loft in Madrid Center,Centro,Embajadores,40.41259,-3.70105,Entire home/apt,NaN,3,0
3,40916,Apartasol Apartamentos Dana,Centro,Universidad,40.42247,-3.70577,Entire home/apt,NaN,5,352
4,62423,MAGIC ARTISTIC HOUSE IN THE CENTER OF MADRID,Centro,Justicia,40.41884,-3.69655,Private room,64.0,1,314

In [8]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26004 entries, 0 to 26003
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   26004 non-null  int64
 1   name                 26004 non-null  object
 2   neighbourhood_group  26004 non-null  object
 3   neighbourhood        26004 non-null  object
 4   latitude             26004 non-null  float64
 5   longitude            26004 non-null  float64
 6   room_type            26004 non-null  object
 7   price                20080 non-null  float64
 8   minimum_nights       26004 non-null  int64
 9   availability_365     26004 non-null  int64
dtypes: float64(3), int64(3), object(4)
memory usage: 2.0+ MB

In [9]:
# analisis de nulos
listings.isnull().sum()

id                        0
name                      0
neighbourhood_group       0
neighbourhood             0
latitude                  0
longitude                 0
room_type                 0
price                  5924
minimum_nights            0
availability_365          0
dtype: int64

In [10]:
# eliminar filas con nulos
listings = listings.dropna()

In [11]:
listings.duplicated().sum()

np.int64(0)

In [12]:
# Value count de todas las variables tipo objeto en listings
for col in listings.select_dtypes(include='object').columns:
    print(f'\n{col}:')
    print(listings[col].value_counts())

name:
name
Habitación en piso compartido                       172
Habitación con baño privado                          30
Habitación en Madrid                                 19
Fantastic residence ``FUNWAY´´ north zone Madrid     16
Habitación piso compartido                           15
                                                   ...
Budu - 2 bedrooms and terrace in Trafalgar            1
De El Retiro al cielo                                 1
Apartamento en Latina                                 1
★ Super Loft Luminoso y amplio en Plaza España ☼      1
Cozy suite - Bravo Murillo                            1
Name: count, Length: 18648, dtype: int64

neighbourhood_group:
neighbourhood_group
Centro                   8372
Tetuán                   1420
Salamanca                1372
Chamberí                 1267
Arganzuela               1008
Retiro                    754
Chamartín                 711
Carabanchel               700
Ciudad Lineal             696
Puente de Vallecas        600
Moncloa - Aravaca         564
Latina                    482
Usera                     468
San Blas - Canillejas     428
Hortaleza                 406
Fuencarral - El Pardo     257
Villaverde                169
Barajas                   137
Moratalaz                 113
Villa de Vallecas          84
Vicálvaro                  72
Name: count, dtype: int64

neighbourhood:
neighbourhood
Embajadores       2134
Universidad       1729
Palacio           1476
Sol               1173
Justicia           989
                  ...
Cuatro Vientos       5
Fuentelareina        5
Horcajo              3
El Pardo             2
Atalaya              1
Name: count, Length: 128, dtype: int64

room_type:
room_type
Entire home/apt    13940
Private room        5944
Shared room          142
Hotel room            54
Name: count, dtype: int64

In [13]:
# eliminar los registros donde room_type sea igual a Hotel room
listings = listings[listings.room_type != "Hotel room"]

In [14]:
listings.iloc[:,7:10].describe().T

,count,mean,std,min,25%,50%,75%,max
price,20026.0,145.040497,485.948741,0.0,64.0,100.0,150.0,32000.0
minimum_nights,20026.0,8.167582,18.057040,1.0,1.0,2.0,4.0,365.0
availability_365,20026.0,202.919105,121.338330,0.0,87.0,220.0,320.0,365.0

In [15]:
# quedarnos con filas cuyo precio sea mayor a 20 y menor que 1000
listings = listings[(listings['price'] >= 20) & (listings['price'] <= 1000)]

In [16]:
listings_det.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,21853,https://www.airbnb.com/rooms/21853,20250612050748,2025-06-26,city scrape,Bright and airy room,We have a quiet and sunny room with a good vie...,We live in a leafy neighbourhood with plenty o...,https://a0.muscache.com/pictures/68483181/87bc...,83531,...,4.82,4.21,4.67,NaN,f,2,0,2,0,0.25
1,30320,https://www.airbnb.com/rooms/30320,20250612050748,2025-06-27,previous scrape,Apartamentos Dana Sol,NaN,NaN,https://a0.muscache.com/pictures/336868/f67409...,130907,...,4.78,4.90,4.69,NaN,f,3,3,0,0,0.94
2,30959,https://www.airbnb.com/rooms/30959,20250612050748,2025-06-27,previous scrape,Beautiful loft in Madrid Center,Beautiful Loft 60m2 size just in the historica...,NaN,https://a0.muscache.com/pictures/78173471/835e...,132883,...,4.63,4.88,4.25,NaN,f,1,1,0,0,0.06
3,40916,https://www.airbnb.com/rooms/40916,20250612050748,2025-06-26,previous scrape,Apartasol Apartamentos Dana,NaN,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,130907,...,4.79,4.88,4.55,NaN,t,3,3,0,0,0.27
4,62423,https://www.airbnb.com/rooms/62423,20250612050748,2025-06-25,city scrape,MAGIC ARTISTIC HOUSE IN THE CENTER OF MADRID,INCREDIBLE HOME OF AN ARTIST SURROUNDED BY PAI...,DISTRICT WITH VERY GOOD VIBES IN THE MIDDLE OF...,https://a0.muscache.com/pictures/miso/Hosting-...,303845,...,4.86,4.97,4.59,NaN,f,3,1,2,0,2.70

In [17]:
listings_det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26004 entries, 0 to 26003
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            26004 non-null  int64
 1   listing_url                                   26004 non-null  object
 2   scrape_id                                     26004 non-null  int64
 3   last_scraped                                  26004 non-null  object
 4   source                                        26004 non-null  object
 5   name                                          26004 non-null  object
 6   description                                   25104 non-null  object
 7   neighborhood_overview                         11158 non-null  object
 8   picture_url                                   26002 non-null  object
 9   host_id                                       26004 non-null  int64
 10  host_url                                      26004 non-null  object
 11  host_name                                     25989 non-null  object
 12  host_since                                    25988 non-null  object
 13  host_location                                 17935 non-null  object
 14  host_about                                    13059 non-null  object
 15  host_response_time                            21276 non-null  object
 16  host_response_rate                            21276 non-null  object
 17  host_acceptance_rate                          22019 non-null  object
 18  host_is_superhost                             25049 non-null  object
 19  host_thumbnail_url                            25988 non-null  object
 20  host_picture_url                              25988 non-null  object
 21  host_neighbourhood                            8629 non-null   object
 22  host_listings_count                           25988 non-null  float64
 23  host_total_listings_count                     25988 non-null  float64
 24  host_verifications                            25988 non-null  object
 25  host_has_profile_pic                          25988 non-null  object
 26  host_identity_verified                        25988 non-null  object
 27  neighbourhood                                 11158 non-null  object
 28  neighbourhood_cleansed                        26004 non-null  object
 29  neighbourhood_group_cleansed                  26004 non-null  object
 30  latitude                                      26004 non-null  float64
 31  longitude                                     26004 non-null  float64
 32  property_type                                 26004 non-null  object
 33  room_type                                     26004 non-null  object
 34  accommodates                                  26004 non-null  int64
 35  bathrooms                                     20065 non-null  float64
 36  bathrooms_text                                25974 non-null  object
 37  bedrooms                                      23550 non-null  float64
 38  beds                                          20069 non-null  float64
 39  amenities                                     26004 non-null  object
 40  price                                         20080 non-null  object
 41  minimum_nights                                26004 non-null  int64
 42  maximum_nights                                26004 non-null  int64
 43  minimum_minimum_nights                        25989 non-null  float64
 44  maximum_minimum_nights                        25989 non-null  float64
 45  minimum_maximum_nights                        25989 non-null  float64
 46  maximum_maximum_nights                        25989 non-null  float64
 47  minimum_nights_avg_ntm                        26004 non-null  float64
 48  maximum_nights_avg_ntm                        26004 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              24483 non-null  object
 51  availability_30                               26004 non-null  int64
 52  availability_60                               26004 non-null  int64
 53  availability_90                               26004 non-null  int64
 54  availability_365                              26004 non-null  int64
 55  calendar_last_scraped                         26004 non-null  object
 56  number_of_reviews                             26004 non-null  int64
 57  number_of_reviews_ltm                         26004 non-null  int64
 58  number_of_reviews_l30d                        26004 non-null  int64
 59  availability_eoy                              26004 non-null  int64
 60  number_of_reviews_ly                          26004 non-null  int64
 61  estimated_occupancy_l365d                     26004 non-null  int64
 62  estimated_revenue_l365d                       20080 non-null  float64
 63  first_review                                  20763 non-null  object
 64  last_review                                   20763 non-null  object
 65  review_scores_rating                          20763 non-null  float64
 66  review_scores_accuracy                        20762 non-null  float64
 67  review_scores_cleanliness                     20761 non-null  float64
 68  review_scores_checkin                         20761 non-null  float64
 69  review_scores_communication                   20762 non-null  float64
 70  review_scores_location                        20759 non-null  float64
 71  review_scores_value                           20758 non-null  float64
 72  license                                       4396 non-null   object
 73  instant_bookable                              26004 non-null  object
 74  calculated_host_listings_count                26004 non-null  int64
 75  calculated_host_listings_count_entire_homes   26004 non-null  int64
 76  calculated_host_listings_count_private_rooms  26004 non-null  int64
 77  calculated_host_listings_count_shared_rooms   26004 non-null  int64
 78  reviews_per_month                             20763 non-null  float64
dtypes: float64(23), int64(20), object(36)
memory usage: 15.7+ MB

In [18]:
a_incluir = ['id',
              'description',
              'accommodates',
              'bathrooms',
              'bedrooms',
              'beds',
              'review_scores_location',
              'estimated_occupancy_l365d'
             ]

listings_det = listings_det[a_incluir]

In [19]:
listings_det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26004 entries, 0 to 26003
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         26004 non-null  int64
 1   description                25104 non-null  object
 2   accommodates               26004 non-null  int64
 3   bathrooms                  20065 non-null  float64
 4   bedrooms                   23550 non-null  float64
 5   beds                       20069 non-null  float64
 6   review_scores_location     20759 non-null  float64
 7   estimated_occupancy_l365d  26004 non-null  int64
dtypes: float64(4), int64(3), object(1)
memory usage: 1.6+ MB

In [20]:
# analisis de nulos
listings_det.isnull().sum()

id                              0
description                   900
accommodates                    0
bathrooms                    5939
bedrooms                     2454
beds                         5935
review_scores_location       5245
estimated_occupancy_l365d       0
dtype: int64

In [21]:
# eliminar registros con estimated_occupancy_l365d = 0
listings_det = listings_det[listings_det['estimated_occupancy_l365d'] != 0]

In [22]:
# analisis de nulos
listings_det.isnull().sum()

id                              0
description                   427
accommodates                    0
bathrooms                    1592
bedrooms                      504
beds                         1592
review_scores_location          1
estimated_occupancy_l365d       0
dtype: int64

In [23]:
listings_det.shape

(17093, 8)

In [24]:
# eliminar registros con accommodates mayores que 8
listings_det = listings_det[listings_det.accommodates <= 8]

In [25]:
# eliminar registros con más de 5 baños
listings_det = listings_det[listings_det.bathrooms <= 5]

In [26]:
# eliminar registros con más de 5 habitaciones
listings_det = listings_det[listings_det.bedrooms <= 5]

In [27]:
# eliminar registros con más de 6 beds
listings_det = listings_det[listings_det.beds <= 6]

In [28]:
# analisis de nulos
listings_det.isnull().sum()

id                             0
description                  375
accommodates                   0
bathrooms                      0
bedrooms                       0
beds                           0
review_scores_location         1
estimated_occupancy_l365d      0
dtype: int64

In [29]:
# comprobar si existen duplicados en listings_det
listings_det.duplicated().sum()

np.int64(0)

In [30]:
listings.info( )

<class 'pandas.core.frame.DataFrame'>
Index: 19793 entries, 0 to 26003
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   19793 non-null  int64
 1   name                 19793 non-null  object
 2   neighbourhood_group  19793 non-null  object
 3   neighbourhood        19793 non-null  object
 4   latitude             19793 non-null  float64
 5   longitude            19793 non-null  float64
 6   room_type            19793 non-null  object
 7   price                19793 non-null  float64
 8   minimum_nights       19793 non-null  int64
 9   availability_365     19793 non-null  int64
dtypes: float64(3), int64(3), object(4)
memory usage: 1.7+ MB

In [31]:
listings.neighbourhood_group.value_counts()

neighbourhood_group
Centro                   8264
Tetuán                   1396
Salamanca                1359
Chamberí                 1252
Arganzuela                998
Retiro                    751
Chamartín                 703
Ciudad Lineal             688
Carabanchel               681
Puente de Vallecas        591
Moncloa - Aravaca         542
Latina                    470
Usera                     467
San Blas - Canillejas     425
Hortaleza                 400
Fuencarral - El Pardo     255
Villaverde                156
Barajas                   135
Moratalaz                 105
Villa de Vallecas          84
Vicálvaro                  71
Name: count, dtype: int64

In [98]:
# Cargar el fichero CSV
ruta_csv = "../datos/brutos/idealista.csv"
df_idealista = pd.read_csv(ruta_csv)

In [99]:
# Renombrar las columnas
df_idealista.columns = ['precio', 'distrito']

# Eliminar el primer registro
df_idealista = df_idealista.iloc[1:].reset_index(drop=True)

In [100]:
df_idealista['precio'] = df_idealista.precio.str.split(expand=True)[0].str.replace('.', '').astype(int)

In [101]:
# Añadimos un nuevo registro con el valor "Vicálvaro" en la columna distrito y en la columna precio el mismo valor que tenga "Moratalaz"
nuevo_registro = df_idealista[df_idealista['distrito'] == 'Moratalaz'].copy()
nuevo_registro['distrito'] = 'Vicálvaro'
df_idealista = pd.concat([df_idealista, nuevo_registro], ignore_index=True)

In [103]:
# Adaptar los nombres de los distritos en df_idealista para que coincidan con listings
mapeo_distritos = {
    'San Blas': 'San Blas - Canillejas',
    'Fuencarral': 'Fuencarral - El Pardo',
    'Moncloa': 'Moncloa - Aravaca',
    # Vicálvaro ya coincide
}
df_idealista['distrito'] = df_idealista['distrito'].replace(mapeo_distritos)

In [104]:
import sqlite3
from sqlite3 import Connection

# Crear la base de datos SQLite
conn: Connection = sqlite3.connect('../datos/intermedios/mercado_inmobiliario.db')

# Guardar listings
listings.to_sql('listings', conn, if_exists='replace', index=False)

# Guardar listings_det
listings_det.to_sql('listings_det', conn, if_exists='replace', index=False)

# Guardar df_idealista
df_idealista.to_sql('idealista', conn, if_exists='replace', index=False)

21

In [105]:
# Comprobar que se han guardado correctamente
print(conn.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall())
print('Filas en listings:', conn.execute('SELECT COUNT(*) FROM listings').fetchone()[0])
print('Filas en listings_det:', conn.execute('SELECT COUNT(*) FROM listings_det').fetchone()[0])
print('Filas en idealista:', conn.execute('SELECT COUNT(*) FROM idealista').fetchone()[0])

conn.close()

[('listings',), ('listings_det',), ('idealista',)]
Filas en listings: 19793
Filas en listings_det: 15132
Filas en idealista: 21